---
title: "p8015_hw6_yl5839"
author: "Yuying Lu"
date: "2024-11-13"
output: github_document
---

```{r setup, include = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)

theme_set(theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") |> 
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |> 
  select(name, id, everything())
```



```{r}
boot_fit = 
  weather_df |> 
  modelr::bootstrap(n = 5000) |> 
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin, data = df)),
    results = map(models, broom::tidy),
    glance = map(models, broom::glance))|> 
    select(-strap, -models)


log_beta = boot_fit |> 
  unnest(results) |> 
  select(.id, term, estimate) |> 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |> 
  rename(hat_b0 = `(Intercept)`, 
         hat_b1 = tmin) |> 
  mutate(log_b = log(hat_b0 * hat_b1))
  
  
r_sq = boot_fit |> 
  unnest(glance) |> 
  select(.id, r.squared) 

est_df = left_join(log_beta, r_sq) |> 
  select(.id, log_b, r.squared) |> 
  pivot_longer(
    log_b:r.squared,
    names_to = 'term',
    values_to = 'estimate'
  )

labels <- as_labeller(c(
  r.squared = "r^2",
  log_b = "log(hat(beta)[0]%*%hat(beta)[1])"), label_parsed)

est_df |> 
  ggplot(aes(x = estimate, fill = term, color = term)) +
  geom_histogram(binwidth = 0.01, alpha = 0.7) +
  labs(title = "Distribution of Estimates from 5000 Bootstrap Samples") +
  facet_grid(~term, labeller = labels)
  
```


```{r}

```

